# Generated by Django 4.1 on 2023-11-16 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("testing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "llm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="testing.llms"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VerifyEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=127)),
                ("code", models.CharField(max_length=6)),
                ("add_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="VerifyMsg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mobile", models.CharField(max_length=11)),
                ("code", models.CharField(max_length=6)),
                ("add_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=32)),
                ("password", models.CharField(max_length=32)),
                ("mobile", models.CharField(max_length=11)),
                ("add_time", models.DateTimeField(auto_now_add=True)),
                ("email", models.CharField(max_length=255, null=True)),
                ("is_admin", models.BooleanField(default=False)),
                (
                    "avatar",
                    models.ImageField(
                        default="static/avatar/default.jpg", upload_to="static/avatar"
                    ),
                ),
                (
                    "subscribed_llm",
                    models.ManyToManyField(
                        through="user.Subscription", to="testing.llms"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="subscription",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user.user"
            ),
        ),
    ]
