# Generated by Django 4.1 on 2023-10-31 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerifyCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mobile", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=255)),
                ("add_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="mobile",
            field=models.CharField(default="", max_length=255),
        ),
    ]
