# Generated by Django 4.1 on 2023-11-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="msg",
            name="target",
            field=models.ManyToManyField(
                related_name="target", through="user.MsgTarget", to="user.user"
            ),
        ),
    ]
