# Generated by Django 4.1 on 2023-10-31 11:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_verifycode_user_mobile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="add_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="mobile",
            field=models.CharField(max_length=255),
        ),
    ]
