# Generated by Django 4.1 on 2023-10-31 12:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_user_add_time_alter_user_mobile"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="VerifyCode",
            new_name="VerifyMsg",
        ),
    ]
