# Generated by Django 4.2.5 on 2023-11-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_verifycode_verifymsg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='verifymsg',
            name='code',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='verifymsg',
            name='mobile',
            field=models.CharField(max_length=11),
        ),
    ]
