# Generated by Django 4.1 on 2023-11-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_alter_user_mobile_alter_user_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
