# Generated by Django 4.1 on 2023-11-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_user_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerifyEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=127)),
                ("code", models.CharField(max_length=6)),
                ("add_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
