# Generated by Django 4.1 on 2023-11-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_verifyemail"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
