# Generated by Django 4.1 on 2023-11-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0008_user_is_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(null=True, upload_to="static/avatar"),
        ),
    ]
