# Generated by Django 4.1 on 2023-11-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=127)),
                ('code', models.CharField(max_length=6)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('new_password', models.CharField(max_length=32)),
            ],
        ),
    ]
