# Generated by Django 4.1 on 2023-11-13 20:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0011_resetpassword"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ResetPassword",
        ),
    ]
