# Generated by Django 4.1 on 2023-11-16 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("testing", "0001_initial"),
        ("dataset", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Credit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("credit", models.IntegerField(null=True)),
                ("add_time", models.DateTimeField(auto_now_add=True)),
                (
                    "LLM",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="testing.llms"
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dataset.dataset",
                    ),
                ),
            ],
        ),
    ]
