# Generated by Django 4.1 on 2023-11-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ranking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="credit",
            name="credit",
            field=models.FloatField(null=True),
        ),
    ]
