# Generated by Django 4.1 on 2023-11-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ranking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credit",
            name="credit",
            field=models.FloatField(null=True),
        ),
    ]
