# Generated by Django 4.1 on 2023-11-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ranking", "0003_datasetlike_llmlike_datasetcomment_like_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasetcomment",
            name="respond",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="llmcomment",
            name="respond",
            field=models.IntegerField(null=True),
        ),
    ]
