# Generated by Django 4.1 on 2023-11-19 21:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ranking", "0004_datasetcomment_respond_llmcomment_respond"),
    ]

    operations = [
        migrations.RenameField(
            model_name="datasetcomment",
            old_name="respond",
            new_name="respond_to",
        ),
        migrations.RenameField(
            model_name="llmcomment",
            old_name="respond",
            new_name="respond_to",
        ),
    ]
