# Generated by Django 4.1 on 2023-11-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ranking", "0005_rename_respond_datasetcomment_respond_to_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasetlike",
            name="dislike",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="llmlike",
            name="dislike",
            field=models.BooleanField(default=False),
        ),
    ]
