from django.urls import path

from . import views

urlpatterns = [
    path(
        "login",
        views.loginView.as_view(),
        name="login"),
    path(
        "login_with_verify_code",
        views.login_with_verify_codeView.as_view(),
        name="login_with_verify_code"),
    path(
        "send_message",
        views.send_messageView.as_view(),
        name="send_message"),
    path(
        "verify_code",
        views.verify_codeView.as_view(),
        name="verify_code"),
    path(
        "register",
        views.registerView.as_view(),
        name="register"),
    path(
        "update/<int:id>",
        views.updateView.as_view(),
        name="update"),
    path(
        "retrieve/<int:id>",
        views.retrieveView.as_view(),
        name="retrieve"),
    path(
        "retrieve_password",
        views.retrievePasswordView.as_view(),
        name="retrieve_password"),
    path(
        "update_avatar",
        views.updateAvatarView.as_view(),
        name="update_avatar"),
    path(
        "logout",
        views.logoutView.as_view(),
        name="logout"),
    path(
        "delete/<int:id>",
        views.deleteView.as_view(),
        name="delete"),
    path(
        "send_email",
        views.send_emailView.as_view(),
        name="send_email"),
    path(
        "verify_email",
        views.verify_emailView.as_view(),
        name="verify_email"),
    path(
        "subscribe_llm",
        views.subscribeLLMView.as_view(),
        name="subscribe_llm"),
    path(
        "subscribe_dataset",
        views.subscribeDatasetView.as_view(),
        name="subscribe_dataset"),
    path(
        "list_llm_subscription/<int:id>",
        views.list_llm_subscriptionView.as_view(),
        name="list_llm_subscription"),
    path(
        "list_dataset_subscription/<int:id>",
        views.list_dataset_subscriptionView.as_view(),
        name="list_dataset_subscription"),
    path(
        "list_message",
        views.list_messageView.as_view(),
        name="list_message"),
    path(
        "create_message",
        views.create_messageView.as_view(),
        name="create_message"),
    path(
        "create_message_to_admin",
        views.create_message_to_adminView.as_view(),
        name="create_message_to_admin"),
    path(
        "check_message",
        views.check_messageView.as_view(),
        name="check_message"),
    path(
        "find_user_by_name",
        views.find_user_by_nameView.as_view(),
        name="find_user_by_name"),
]
