# Generated by Django 4.1 on 2023-11-16 01:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LLMs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=127)),
                (
                    "api_url",
                    models.CharField(
                        default="https://api.openai.com/v1/chat/completions",
                        max_length=255,
                    ),
                ),
                (
                    "api_headers",
                    models.TextField(
                        default='{"Authorization":"Bearer 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"}'
                    ),
                ),
                (
                    "api_data",
                    models.TextField(
                        default='{"model": "gpt-3.5-turbo","messages": [{"role": "user", "content": "$PROMPT"}],"temperature": 0.7}'
                    ),
                ),
                ("api_RPM", models.IntegerField(default=3, null=True)),
                ("description", models.TextField(default="")),
                ("add_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
