# Generated by Django 4.1 on 2023-11-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="llms",
            name="elo_credit",
            field=models.FloatField(default=1500),
        ),
    ]
