# Generated by Django 4.1 on 2023-11-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="llms",
            name="released_time",
            field=models.CharField(default="", max_length=255),
        ),
    ]
