# Generated by Django 4.1 on 2023-11-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="llms",
            name="api_url",
            field=models.CharField(
                default="https://api.openai.com/v1/chat/completions", max_length=255
            ),
        ),
    ]
