# Generated by Django 4.1 on 2023-11-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testing", "0002_llms_api_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="llms",
            name="api_data",
            field=models.TextField(
                default='{"model": "gpt-3.5-turbo","messages": [{"role": "user", "content": "$PROMPT"}],"temperature": 0.7}'
            ),
        ),
        migrations.AddField(
            model_name="llms",
            name="api_headers",
            field=models.TextField(
                default='{"Authorization":"Bearer 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"}'
            ),
        ),
    ]
