# Generated by Django 4.1 on 2023-11-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testing", "0002_llms_elo_credit"),
    ]

    operations = [
        migrations.AddField(
            model_name="llms",
            name="authentication",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="llms",
            name="document_name",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="llms",
            name="document_website",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="llms",
            name="logo",
            field=models.ImageField(
                default="static/logo/default.jpg", upload_to="static/logo"
            ),
        ),
        migrations.AddField(
            model_name="llms",
            name="official_website",
            field=models.CharField(default="", max_length=255),
        ),
    ]
