# Generated by Django 4.1 on 2023-11-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testing", "0003_llms_api_data_llms_api_headers"),
    ]

    operations = [
        migrations.AddField(
            model_name="llms",
            name="api_RPM",
            field=models.IntegerField(null=True),
        ),
    ]
