# Generated by Django 4.1 on 2023-11-20 18:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("testing", "0003_llms_authentication_llms_document_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="llms",
            old_name="authentication",
            new_name="license",
        ),
    ]
