# Generated by Django 4.1 on 2023-11-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testing", "0004_rename_authentication_llms_license"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="llms",
            name="api_data",
        ),
        migrations.RemoveField(
            model_name="llms",
            name="api_headers",
        ),
        migrations.AddField(
            model_name="llms",
            name="model_name",
            field=models.CharField(default="mistral_7b", max_length=255),
        ),
        migrations.AlterField(
            model_name="llms",
            name="api_RPM",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="llms",
            name="api_url",
            field=models.CharField(
                default="http://111.202.73.146:10510/v1/chat/completions",
                max_length=255,
            ),
        ),
    ]
