# Generated by Django 4.1 on 2023-11-15 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0012_delete_resetpassword"),
        ("testing", "0004_llms_api_rpm"),
    ]

    operations = [
        migrations.AddField(
            model_name="llms",
            name="author",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="user.user"
            ),
        ),
        migrations.AddField(
            model_name="llms",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="llms",
            name="api_RPM",
            field=models.IntegerField(default=3, null=True),
        ),
    ]
