# Generated by Django 4.1 on 2023-11-24 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("testing", "0005_remove_llms_api_data_remove_llms_api_headers_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BattleHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round", models.IntegerField()),
                ("result", models.JSONField()),
                ("user_id", models.IntegerField()),
                ("winner", models.IntegerField()),
                ("add_time", models.DateTimeField(auto_now_add=True)),
                (
                    "llm1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm1",
                        to="testing.llms",
                    ),
                ),
                (
                    "llm2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm2",
                        to="testing.llms",
                    ),
                ),
            ],
        ),
    ]
